options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'maven:3.9.0-eclipse-temurin-17'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/moon-tracker/agent/agent-service', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/moon-tracker/agent/agent-service']

images:
  - 'us-central1-docker.pkg.dev/moon-tracker/agent/agent-service'
